# Generated by Django 4.2.30 on 2026-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("task_completed", "Task completed"),
                    ("task_cancelled", "Task cancelled"),
                    ("task_stuck", "Task cannot be assigned to anyone"),
                ],
                max_length=32,
            ),
        ),
    ]
