# Generated by Django 4.2.30 on 2026-08-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0002_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleeligibleuser",
            name="rule",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eligible",
                to="assignment.rule",
            ),
        ),
        migrations.AlterField(
            model_name="ruleeligibleuser",
            name="user",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eligible_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
