# Generated by Django 4.2.30 on 2026-08-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0003_alter_ruleeligibleuser_rule_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
