# Generated by Django 4.2.30 on 2026-08-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0004_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="placement_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
